FROM python:3.11-slim

# Ajustes de rede/tempo para redes lentas ou com inspeção SSL
RUN python -m pip install --upgrade pip \
 && pip config set global.timeout 120 \
 && pip config set global.retries 20

WORKDIR /app
COPY apps/bff/requirements.txt /tmp/requirements.txt
RUN pip install --no-cache-dir -r /tmp/requirements.txt

# diretório de trabalho do app
WORKDIR /app/apps/bff
CMD ["uvicorn","app.main:APP","--host","0.0.0.0","--port","8000","--reload"]
