FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Código do BFF
COPY app ./app
COPY run_dev.sh ./run_dev.sh
RUN chmod +x /app/run_dev.sh

# Porta do Uvicorn
EXPOSE 8000

CMD ["./run_dev.sh"]
