# infra/docs.Dockerfile
FROM python:3.12-slim

# Boa prática p/ logs/sinais e evitar __pycache__
ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PIP_NO_CACHE_DIR=1 \
    PIP_DISABLE_PIP_VERSION_CHECK=1

# Apenas o necessário
RUN apt-get update && apt-get install -y --no-install-recommends \
      ca-certificates tini \
    && rm -rf /var/lib/apt/lists/*

# Pip atualizado + plugins
RUN python -m pip install --upgrade pip && \
    pip install \
      mkdocs==1.6.1 \
      mkdocs-material==9.6.18 \
      mkdocs-glightbox==0.4.0 \
      mkdocs-swagger-ui-tag==0.6.7 \
      mkdocs-mermaid2-plugin==1.2.1

# (Opcional) usuário não-root
RUN useradd -m -u 10001 app
USER app

WORKDIR /workspace
EXPOSE 8000

ENTRYPOINT ["/usr/bin/tini","--"]
CMD ["mkdocs","serve","-a","0.0.0.0:8000"]
